version: '2.1'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:110.0
    logging:
      driver: none
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2G
#    ports:
#      - "4444:4444"
    network_mode: "host"
    environment:
      - SE_NODE_MAX_SESSIONS=200
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SESSION_REQUEST_TIMEOUT=400
      - SE_SESSION_RETRY_INTERVAL=2


